# Generated by Django 5.0.1 on 2025-11-18 05:10

import apps.users.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_add_course_review_fields"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.users.models.generate_lesson_progress_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completada"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de finalización"
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Porcentaje de progreso en la lección (ej: 50% visto de un video)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Porcentaje de progreso",
                    ),
                ),
                (
                    "time_watched_seconds",
                    models.IntegerField(
                        default=0,
                        help_text="Tiempo total visto en la lección (útil para videos)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tiempo visto (segundos)",
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Último acceso"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos adicionales"
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        help_text="Enrollment asociado (para validar acceso)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progresses",
                        to="users.enrollment",
                        verbose_name="Inscripción",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="courses.lesson",
                        verbose_name="Lección",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Lección",
                "verbose_name_plural": "Progresos de Lecciones",
                "db_table": "lesson_progress",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "enrollment"],
                        name="lesson_prog_user_id_34b577_idx",
                    ),
                    models.Index(
                        fields=["lesson", "is_completed"],
                        name="lesson_prog_lesson__7f1273_idx",
                    ),
                    models.Index(
                        fields=["enrollment", "is_completed"],
                        name="lesson_prog_enrollm_9b2eb0_idx",
                    ),
                ],
                "unique_together": {("user", "lesson", "enrollment")},
            },
        ),
    ]
