# Generated by Django 5.0.1 on 2025-11-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("instructor", "Instructor"),
                    ("student", "Estudiante"),
                    ("guest", "Invitado"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
