# Generated by Django 5.0.1 on 2025-11-17 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_update_role_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="instructor_approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que el instructor fue aprobado",
                null=True,
                verbose_name="Fecha de Aprobación",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="instructor_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrador que aprobó al instructor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_instructors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprobado por",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="instructor_rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Razón por la cual el instructor fue rechazado (si aplica)",
                null=True,
                verbose_name="Razón de Rechazo",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="instructor_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending_approval", "Pendiente de Aprobación"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                ],
                help_text="Estado de aprobación para usuarios con rol instructor",
                max_length=20,
                null=True,
                verbose_name="Estado de Instructor",
            ),
        ),
    ]
