# Generated by Django 5.0.1 on 2025-11-21 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_create_instructor_application"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="instructorapplication",
            new_name="instructor__status_070ef4_idx",
            old_name="instructor_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="instructorapplication",
            new_name="instructor__user_id_295a5a_idx",
            old_name="instructor_user_status_idx",
        ),
    ]
