# Generated by Django 5.0.1 on 2025-12-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0005_rename_instructor_status_created_idx_instructor__status_070ef4_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Teléfono")),
                ("message", models.TextField(max_length=2000, verbose_name="Mensaje")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nuevo"),
                            ("read", "Leído"),
                            ("replied", "Respondido"),
                            ("archived", "Archivado"),
                        ],
                        default="new",
                        help_text="Estado del mensaje",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas internas sobre este mensaje",
                        max_length=1000,
                        null=True,
                        verbose_name="Notas del Administrador",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que el mensaje fue leído por primera vez",
                        null=True,
                        verbose_name="Fecha de Lectura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Contacto",
                "verbose_name_plural": "Mensajes de Contacto",
                "db_table": "contact_messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="contact_mes_status_060932_idx",
                    ),
                    models.Index(
                        fields=["email", "-created_at"],
                        name="contact_mes_email_edd3a9_idx",
                    ),
                ],
            },
        ),
    ]
