# Generated by Django 5.0.1 on 2025-11-12 17:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(
                blank=True, default="General", max_length=100, verbose_name="Categoría"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Precio con descuento",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="hours",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Horas totales",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON con id, name, title del instructor",
                verbose_name="Instructor",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Principiante"),
                    ("intermediate", "Intermedio"),
                    ("advanced", "Avanzado"),
                ],
                default="beginner",
                max_length=20,
                verbose_name="Nivel",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="provider",
            field=models.CharField(
                default="fagsol",
                help_text="fagsol o instructor",
                max_length=50,
                verbose_name="Proveedor",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("5.00")),
                ],
                verbose_name="Calificación",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="ratings_count",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Número de calificaciones",
            ),
        ),
    ]
