# Generated by Django 5.0.1 on 2025-11-18 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_category_course_discount_price_course_hours_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="review_comments",
            field=models.TextField(
                blank=True,
                help_text="Comentarios del administrador sobre la revisión (máximo 2000 caracteres)",
                max_length=2000,
                null=True,
                verbose_name="Comentarios de Revisión",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que se realizó la revisión",
                null=True,
                verbose_name="Fecha de Revisión",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Administrador que revisó el curso",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revisado por",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("pending_review", "Pendiente de Revisión"),
                    ("needs_revision", "Requiere Cambios"),
                    ("published", "Publicado"),
                    ("archived", "Archivado"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
