# Generated by Django 5.0.1 on 2025-11-18 05:48

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_add_course_review_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="id",
            field=models.CharField(
                default=apps.courses.models.generate_lesson_id,
                help_text="ID único de la lección",
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="id",
            field=models.CharField(
                default=apps.courses.models.generate_module_id,
                help_text="ID único del módulo (ej: m-001)",
                max_length=50,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
