# Generated by Django 5.0.1 on 2025-11-23 12:53

import apps.courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_add_default_ids_module_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.courses.models.generate_material_id,
                        help_text="ID único del material",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[("video", "Video Vimeo"), ("link", "Enlace Externo")],
                        default="video",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL del video de Vimeo o enlace externo",
                        verbose_name="URL",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="courses.lesson",
                        verbose_name="Lección (opcional)",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="courses.module",
                        verbose_name="Módulo (opcional)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materiales",
                "db_table": "materials",
                "ordering": ["course", "order"],
                "indexes": [
                    models.Index(
                        fields=["course", "order"], name="materials_course__d6ca7a_idx"
                    ),
                    models.Index(
                        fields=["module"], name="materials_module__ae0ef7_idx"
                    ),
                    models.Index(
                        fields=["lesson"], name="materials_lesson__c20660_idx"
                    ),
                ],
            },
        ),
    ]
