# Generated by Django 5.0.1 on 2025-12-05 10:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_add_material_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio base en dólares estadounidenses (USD)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Precio en USD",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Precio en PEN (Soles) - calculado desde price_usd",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Precio",
            ),
        ),
    ]
