# Generated by Django 5.0.1 on 2026-02-26 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="announcement",
            new_name="announcemen_active_96b1c3_idx",
            old_name="announcement_active_8a1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="announcement",
            new_name="announcemen_slug_b1a99c_idx",
            old_name="announcement_slug_9d4e5f_idx",
        ),
    ]
