# Generated by Django 5.0.1 on 2025-11-12 04:53

import apps.payments.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.payments.models.generate_payment_intent_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Total",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="PEN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("succeeded", "Exitoso"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "course_ids",
                    models.JSONField(
                        default=list,
                        help_text="Lista de IDs de cursos",
                        verbose_name="IDs de cursos",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos adicionales"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expira en"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Intent",
                "verbose_name_plural": "Payment Intents",
                "db_table": "payment_intents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.payments.models.generate_payment_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="PEN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("refunded", "Reembolsado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "mercado_pago_payment_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID de pago Mercado Pago",
                    ),
                ),
                (
                    "mercado_pago_status",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Estado Mercado Pago",
                    ),
                ),
                (
                    "mercado_pago_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Respuesta completa de Mercado Pago",
                    ),
                ),
                (
                    "payment_token",
                    models.CharField(
                        blank=True,
                        help_text="Token de Mercado Pago (NO datos de tarjeta)",
                        max_length=200,
                        null=True,
                        verbose_name="Token de pago",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Clave de idempotencia",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos adicionales"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "payment_intent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="payments.paymentintent",
                        verbose_name="Payment Intent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhook",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mercado_pago_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="ID de webhook Mercado Pago",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="Tipo de evento"),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID de pago relacionado",
                    ),
                ),
                (
                    "data",
                    models.JSONField(default=dict, verbose_name="Datos del webhook"),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Procesado"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de procesamiento"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de recepción"
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook de Pago",
                "verbose_name_plural": "Webhooks de Pago",
                "db_table": "payment_webhooks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["mercado_pago_id"],
                        name="payment_web_mercado_5be617_idx",
                    ),
                    models.Index(
                        fields=["payment_id"], name="payment_web_payment_17beb2_idx"
                    ),
                    models.Index(
                        fields=["processed", "created_at"],
                        name="payment_web_process_79839b_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["user", "status"], name="payment_int_user_id_f69c6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["status", "created_at"], name="payment_int_status_1c0031_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="payments_user_id_1b771c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payments_status_426d4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["idempotency_key"], name="payments_idempot_1c73ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["mercado_pago_payment_id"], name="payments_mercado_b3e5b6_idx"
            ),
        ),
    ]
